// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfqbjjrqgzvdpklmcrog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcWJqanJxZ3p2ZHBrbG1jcm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDI4MDMsImV4cCI6MjA2NTgxODgwM30.9IRsKfmXhncn6yFZWyzJOpCUyjibdi4dDN2fSh7r3hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);